#    COPYRIGHT (C) 2025 Mitsubishi Electric Corporation

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    Contributor(s):
#       Liu Muyao

# This is a sample message that maps HMI input buttons and output lamps to a boolean variable.

bool button_0
bool button_1
bool button_2
bool button_3
bool button_4
bool button_5
bool button_6
bool button_7
bool button_8
bool button_9
bool button_10
bool button_11
bool button_12
bool button_13
bool button_14
bool button_15

